

const arrayDeCuentos = [
    {
        id: "0",
        genero: "aventuras",
        personaje: "dinosaurio",
        lugar: "castillo",
        elemento: "varita",
        nombre: "aventurasDinosaurioCastilloVarita",
    },
    {
        id: "1",
        genero: "aventuras",
        personaje: "dinosaurio",
        lugar: "castillo",
        elemento: "bicicleta",
        nombre: "aventurasDinosaurioCastilloBicicleta",
    },
    {
        id: "2",
        genero: "aventuras",
        personaje: "dinosaurio",
        lugar: "castillo",
        elemento: "cohete",
        nombre: "aventurasDinosaurioCastilloCohete", 
    },
    {
        id: "3",
        genero: "aventuras",
        personaje: "dinosaurio",
        lugar: "bosque",
        elemento: "varita",
        nombre: "aventurasDinosaurioBosqueVarita",
    },
    {
        id: "4",
        genero: "aventuras",
        personaje: "dinosaurio",
        lugar: "bosque",
        elemento: "bicicleta",
        nombre: "aventurasDinosaurioBosqueBicicleta",
    },
    {
        id: "5",
        genero: "aventuras",
        personaje: "dinosaurio",
        lugar: "bosque",
        elemento: "cohete",
        nombre: "aventurasDinosaurioBosqueCohete",
    }, 
    {
        id: "6",
        genero: "aventuras",
        personaje: "dinosaurio",
        lugar: "espacio",
        elemento: "varita",
        nombre: "aventurasDinosaurioEspacioVarita",
    },
    {
        id: "7",
        genero: "aventuras",
        personaje: "dinosaurio",
        lugar: "espacio",
        elemento: "bicicleta",
        nombre: "aventurasDinosaurioEspacioBicicleta",
    },
    {
        id: "8",
        genero: "aventuras",
        personaje: "dinosaurio",
        lugar: "espacio",
        elemento: "cohete",
        nombre: "aventurasDinosaurioEspacioCohete",
    },
    {
        id: "9",
        genero: "aventuras",
        personaje: "unicornio",
        lugar: "castillo",
        elemento: "varita",
        nombre: "aventurasUnicornoCastilloVarita",
    },
    {
        id: "10",
        genero: "aventuras",
        personaje: "unicornio",
        lugar: "castillo",
        elemento: "bicicleta",
        nombre: "aventurasUnicornoCastilloBicicleta",
    },
    {
        id: "11",
        genero: "aventuras",
        personaje: "unicornio",
        lugar: "bosque",
        elemento: "cohete",
        nombre: "aventurasUnicornioBosqueCohete",
    },
    {
        id: "12",
        genero: "aventuras",
        personaje: "unicornio",
        lugar: "bosque",
        elemento: "varita",
        nombre: "aventuraUnicornioBosqueVarita",
    },
    {
        id: "13",
        genero: "aventuras",
        personaje: "unicornio",
        lugar: "bosque",
        elemento: "bicicleta",
        nombre: "aventurasUnicornioBosqueBicicleta",
    },
    {
        id: "14",
        genero: "aventuras",
        personaje: "unicornio",
        lugar: "bosque",
        elemento: "cohete",
        nombre:  "aventurasUnicornioBosqueCohete",
    },
    {
        id: "15",
        genero: "aventuras",
        personaje: "unicornio",
        lugar: "espacio",
        elemento: "varita",
        nombre: "aventuraUnicornioEspacioVarita",
    },
    {
        id: "16",
        genero: "aventuras",
        personaje: "unicornio",
        lugar: "espacio",
        elemento: "bicicleta",
        nombre: "aventuraUnicornioEspacioBicicleta",
    },
    {
        id: "17",
        genero: "aventuras",
        personaje: "unicornio",
        lugar: "espacio",
        elemento: "bicicleta",
        nombre: "aventuraUnicornioEspacioBicicleta",
    },
    {
        id: "19",
        genero: "aventuras",
        personaje: "astronauta",
        lugar: "castillo",
        elemento: "varita",
        nombre: "aventurasAstronautaCastilloVarita",
    },
    {
        id: "20",
        genero: "aventuras",
        personaje: "astronauta",
        lugar: "castillo",
        elemento: "cohete",
        nombre: "aventurasAstronautaCastilloCohete",
    },
    {
        id: "21",
        genero: "aventuras",
        personaje: "astronauta",
        lugar: "bosque",
        elemento: "varita",
        nombre: "aventurasAstronautaBosqueVarita",
    },
    {
        id: "22",
        genero: "aventuras",
        personaje: "astronauta",
        lugar: "bosque",
        elemento: "bicicleta",
        nombre: "aventurasAstronautaBosqueBicicleta",
    },
    {
        id: "23",
        genero: "aventuras",
        personaje: "astronauta",
        lugar: "bosque",
        elemento: "cohete",
        nombre: "aventurasAstronautaBosqueCohete",
    },
    {
        id: "24",
        genero: "aventuras",
        personaje: "astronauta",
        lugar: "bosque",
        elemento: "cohete",
        nombre: "aventurasAstronautaEspacioVarita",
    },
    {
        id: "25",
        genero: "aventuras",
        personaje: "astronauta",
        lugar: "espacio",
        elemento: "bicicleta",
        nombre: "aventurasAstronautaEspacioBicicleta",
    },
    {
        id: "26",
        genero: "aventuras",
        personaje: "astronauta",
        lugar: "espacio",
        elemento: "cohete",
        nombre: "aventurasAstronautaEspacioCohete",
    },
    {
        id: "27",
        genero: "risas",
        personaje: "dinosaurio",
        lugar: "castillo",
        elemento: "varita",
        nombre: "risasDinosaurioCastilloVarita",
    },
    {
        id: "28",
        genero: "risas",
        personaje: "dinosaurio",
        lugar: "castillo",
        elemento: "varita",
        nombre: "risasDinosaurioCastilloVarita",
    },
    {
        id: "29",
        genero: "risas",
        personaje: "dinosaurio",
        lugar: "castillo",
        elemento: "bicicleta",
        nombre: "risasDinosaurioCastilloBicicleta",
    },
    {
        id: "30",
        genero: "risas",
        personaje: "dinosaurio",
        lugar: "castillo",
        elemento: "cohete",
        nombre: "risasDinosaurioCastilloCohete",
    },
    {
        id: "31",
        genero: "risas",
        personaje: "dinosaurio",
        lugar: "bosque",
        elemento: "varita",
        nombre: "risasDinosaurioBosqueVarita",
    },
    {
        id: "32",
        genero: "risas",
        personaje: "dinosaurio",
        lugar: "bosque",
        elemento: "bicicleta",
        nombre: "risasDinosaurioBosqueBicicleta",
    },
    {
        id: "33",
        genero: "risas",
        personaje: "dinosaurio",
        lugar: "bosque",
        elemento: "cohete",
        nombre: "risasDinosaurioBosqueCohete",
    },
    {
        id: "34",
        genero: "risas",
        personaje: "dinosaurio",
        lugar: "espacio",
        elemento: "varita",
        nombre: "risasDinosaurioEspacioVarita",
    },
    {
        id: "35",
        genero: "risas",
        personaje: "dinosaurio",
        lugar: "espacio",
        elemento: "bicicleta",
        nombre: "risasDinosaurioEspacioBicicleta",
    },
    {
        id: "36",
        genero: "risas",
        personaje: "dinosaurio",
        lugar: "espacio",
        elemento: "cohete",
        nombre: "risasDinosaurioEspacioCohete",
    },
    
    "risasDinosaurioEspacioCohete",
    "risasUnicornoCastilloVarita",
    "risasUnicornoCastilloBicicleta",
    "risasUnicornoCastilloCohete",
    "risasUnicornioBosqueVarita",
    "risasUnicornioBosqueBicicleta",
    "risasUnicornioBosqueCohete",
    "risasUnicornioEspacioVarita",
    "risasUnicornioEspacioBicicleta",
    "aventuraUnicornioEspacioCohete",
    "risasAstronautaCastilloVarita",
    "risasAstronautaCastilloBicicleta",
    "risasAstronautaCastilloCohete",
    "risasAstronautaBosqueVarita",
    "risasAstronautaBosqueBicicleta",
    "risasAstronautaBosqueCohete",
    "risasAstronautaEspacioVarita",
    "risasAstronautaEspacioBicicleta",
    "risasAstronautaEspacioCohete",
    "fantasiasDinosaurioCastilloVarita",
    "fantasiasDinosaurioCastilloBicicleta",
    "fantasiasDinosaurioCastilloChoete",
    "fantasiasDinosaurioBosqueVarita",
    "fantasiasDinosaurioBosqueBicicleta",
    "fantasiasDinosaurioBosqueCohete",
    "fantasiasDinosaurioEspacioVarita",
    "fantasiasDinosaurioEspacioBicicleta",
    "fantasiasDinosaurioEspacioCohete",
    "fantasiasUnicornoCastilloVarita",
    "fantasiasUnicornoCastilloBicicleta",
    "fantasiasUnicornoCastilloCohete",
    "fantasiasUnicornioBosqueVarita",
    "fantasiasUnicornioBosqueBicicleta",
    "fantasiasUnicornioBosqueCohete",
    "fantasiasUnicornioEspacioVarita",
    "fantasiasUnicornioEspacioBicicleta",
    "fantasiasUnicornioEspacioCohete",
    "fantasiasAstronautaCastilloVarita",
    "fantasiasAstronautaCastilloBicicleta",
    "fantasiasAstronautaCastilloCohete",
    "fantasiasAstronautaBosqueVarita",
    "fantasiasAstronautaBosqueBicicleta",
    "fantasiasAstronautaBosqueCohete",
    "fantasiasAstronautaEspacioVarita",
    "fantasiasAstronautaEspacioBicicleta",
    "fantasiasAstronautaEspacioCohete",];

console.log(arrayDeCuentos)




